version: '3'
services:
  minio:
    image: minio/minio:latest
    container_name: minio_server
    ports:
      - "9000:9000"  # Expose MinIO on port 9000
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: your_username_here
      MINIO_ROOT_PASSWORD: your_password_here
    volumes:
      - ./data:/data  # Map the local 'data' folder to MinIO data folder
    command: server /data --console-address ":9090"
    restart: unless-stopped  # Restart the container unless stopped manually
